// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace these with your actual Firebase project configuration
  // You can find these values in your Firebase project settings
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgkiwD2mqwUPvqELIwzu-6WSEqYV4Pz9c',
    appId: '1:3037584400:web:cfffd5c8887448d367fe95',
    messagingSenderId: '3037584400',
    projectId: 'habit-tracker-3c70b',
    authDomain: 'habit-tracker-3c70b.firebaseapp.com',
    storageBucket: 'habit-tracker-3c70b.firebasestorage.app',
  );

      static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyCY0VUnWSS2cxp2z-ixPWHnZBkiONl3ZFM',
      appId: '1:3037584400:android:84c29f6a18ef702967fe95',
      messagingSenderId: '3037584400',
      projectId: 'habit-tracker-3c70b',
      storageBucket: 'habit-tracker-3c70b.firebasestorage.app',
    );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'habit-tracker-3c70b',
    storageBucket: 'habit-tracker-3c70b.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'habit-tracker-3c70b',
    storageBucket: 'habit-tracker-3c70b.appspot.com',
    iosClientId: 'YOUR_MACOS_CLIENT_ID',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'habit-tracker-3c70b',
  );
} 